### ISSUE TITLE
现存在的问题，Existing problems

### ISSUE THREAD

**Issue by asdzxc93** [pissarro-dev/OTA#2] opened 2023-12-18 13:15 UTC
中文
1，（非重要）无nfc，无双击亮屏
2,（重要）麦克风的收音小
3，（不确定的问题）通话中麦克风会录入手机的声音

English
1. (Non important) No NFC, no double click on screen
2. (Important) The microphone's reception is low
3. (Uncertain issue) During a call, the microphone will input the sound of the phone

**Comment by swety2003** [comment] 2023-12-28 04:27
Fingerprint authentication doesnt working in Wechat Pay and AliPay.

**Comment by jieran233** [comment] 2024-01-01 13:00
Based on my usage experience in the past few days, regarding issues related to calls, the actual problem may be more complex than the sentence in the release notes.

- For the first call after booting up, the call sound is not audible at all.
- After the second call ends, wired headphones do not produce any sound, including media playback.
- Opening and then closing the speakerphone during a call seems to solve the above two issues.
- The call volume seems to depend on the media volume slider at times and the call volume slider at other times.

The above content is very uncertain and obviously not an exact reproduction process of the bug. This problem is still unclear at least for me. Anyway, I hope the developers can fix it. Happy New Year!

<details>
<summary>中文</summary>

据我这几天的使用经历，关于通话相关的问题，实际的问题可能比Release中的那一句话更复杂

- 对于开机首次通话，是无论如何都听不见通话声音的
- 第二次通话结束后，有线耳机是听不见任何声音的，包括媒体播放
- 在通话时打开再关闭免提似乎可以解决以上两个问题
- 通话音量似乎有时取决于媒体音量滑块，有时取决于通话音量滑块

以上内容是很不确定的，显然不是确切的BUG复现流程，至少对我来说这个问题还很模糊。但无论如何，祝愿开发者能够修复它，新年快乐！

</details>

**Comment by jieran233** [comment] 2024-01-03 16:37
By the way, has anyone encountered the problem of a slight noise similar to the sound of current appearing in the left channel of the headset when playing sound (especially obvious when the sound effect is played when the charging cable is plugged in or unplugged, which can be verified through this),  I encountered this strange problem, but I'm not sure if it's a ROM problem or a problem with my phone. Although it seems unlikely that it's a ROM problem, I still hope to get your reply. Thank you.

<details> <summary>中文</summary>

顺便问一下，有没有任何人遇到耳机左声道在播放声音时出现类似电流声的轻微噪音的问题（在插入或拔出充电线时播放的音效下尤为明显，可以通过这来验证），我遇到了这个奇怪的问题，但我不确定是ROM的问题还是我手机的问题，虽然看起来不太可能是ROM的问题但我还是希望能得到各位的回复谢谢

</details>

**Comment by jieran233** [comment] 2024-01-05 04:14
I also noticed another issue, but I'm not sure if it's caused by this ROM, even though I have never faced that issue before using MIUI on this phone, your feedback is crucial:

sometimes there is a white noise in the left channel of the speaker and wired headphones (In a quiet environment, you can clearly hear it at the left channel of the speaker by putting your ear close to it)

For example, **it is noticeable on the lock screen when the screen lights up**, or during the playback of any audio
(especially quieter music in low volume, and the notification sound when inserting or removing the charging cable)

Sorry if this issue is not caused by this ROM.

<details>
<summary>中文</summary>

我还注意到另一个问题，但我不确定它是否由此ROM引起，即使我从未在之前在这部手机上使用MIUI时遇到过该问题，各位的反馈至关重要：

有时扬声器和有线耳机的左声道中会出现白噪音（在安静的环境中将耳朵靠近扬声器的左声道可以清楚听到）

例如，**点亮屏幕在锁定屏幕**，或在任何音频播放期间（尤其是低音量的安静音乐以及插拔充电线时的提示音）

如果这个问题不是由这个ROM引起的，我很抱歉。

</details>

**Closed as completed** 2024-01-12 01:07 UTC
